Algoritmo "enquanto pares_consecutivos"

Var
   X, soma : inteiro



Inicio
      escreva("Digite um numero inteiro: ")
      leia(x)
      
      enquanto X <> 0 faca 
      
         se X % 2 <>0 entao
            x <- x + 1
         fimse

         soma <- 5 * X + 20
         escreval("SOMA = ", soma)
         
         escreva("Digite um numero inteiro: ")
         leia(x)
      fimenquanto
      


Fimalgoritmo