Algoritmo "Exercicio_de_Fixacao_2"

Var

     b1, b2, h, area : real
     
     a, b, resultado : inteiro
     
     d : real
     f : inteiro
     
Inicio

      b1 <- 6.0
      b2 <- 8.0
      h <- 5.0

      area <- (b1 + b2) / 2.0 * h;
      
      escreval(area)
      escreval

      a <- 5
      b <- 2
      resultado <- a \ b
      escreval(resultado)
      escreval
      
      d <- 5.0
      f <- int(d)
      escreval(f)

      

Fimalgoritmo